image: registry.gitlab.com/aplus-framework/images/lempa:2

include:
  - template: Security/SAST.gitlab-ci.yml

pages:
  stage: deploy
  timeout: 10 minutes
  dependencies:
    - test:php
  environment:
    name: production
    url: https://aplus-framework.gitlab.io
  script:
    - mv public/ app-public/
    - mkdir public/
    - mv build/coverage/ public/
    - mv build/docs/ public/
  artifacts:
    paths:
      - public/
  only:
    - master
